# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: James Kruth
author:
  name: James Kruth
  email: james@kruth.org
description: > # this means to ignore newlines until "url:"
  I program computers and make things
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://james.kruth.org" # the base hostname & protocol for your site

license: > # the license for your site - optional
  This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">Creative Commons BY-NC-SA 4.0 License</a>.
powered_by: false  # display the powered by and theme info in the footer

# Build settings
exclude: ['Gemfile', 'Gemfile.lock', 'README.md', 'LICENSE']
permalink: pretty

kramdown:
  input: GFM

# plugins
gems:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# deploy
deploy:
  - "rsync -crvz --delete-after --delete-excluded ./ artlogic_jkorg@ssh.phx.nearlyfreespeech.net:"
